name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 17.0.6
          distribution: "temurin"

      - name: Build with Maven
        working-directory: daily-tracker
        run: mvn clean install

      - name: Run Tests
        working-directory: daily-tracker
        run: java -jar lib/junit-platform-console-standalone-1.9.3.jar --class-path target/test-classes --scan-classpath
